/** IT / cloud stock photos in public/images/ (Pexels). Replace with your own assets anytime. */
export const placeholders = {
  heroAzure: "/images/hero-azure-linux.jpg",
  heroDevops: "/images/hero-devops-azure.png",
  heroStartup: "/images/hero-startup.jpg",
  serviceTraining: "/images/training.jpg",
  serviceStartup: "/images/startup-team.jpg",
  intro: "/images/intro.jpg",
  about: "/images/about.jpg",
  aboutStory: "/images/about-story.jpg",
  valueClarity: "/images/value-clarity.jpg",
  valuePractice: "/images/value-practice.jpg",
  valueResponsiveness: "/images/value-responsiveness.jpg",
  contact: "/images/contact.jpg",
  process: "/images/process.jpg",
  team: "/images/team.jpg",
  trainingBanner: "/images/training-banner.jpg",
  startupBanner: "/images/startup-banner.jpg",
  programAzure: "/images/program-azure.jpg",
  programDevops: "/images/program-devops.jpg",
  cloudInfra: "/images/cloud-infra.jpg",
  l1l2: "/images/l1l2-support.jpg",
  servers: "/images/servers.jpg",
  contactTraining: "/images/contact-training.jpg",
  contactStartup: "/images/contact-startup.jpg",
} as const;
